// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/zap/zapcore/encoder.go

// Package mock_zapcore is a generated GoMock package.
package mock_zapcore

import (
	reflect "reflect"
	time "time"

	zapcore "go.uber.org/zap/zapcore"
	gomock "github.com/golang/mock/gomock"
	buffer "go.uber.org/zap/buffer"
)

// MockObjectEncoder is a mock of ObjectEncoder interface.
type MockObjectEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockObjectEncoderMockRecorder
}

// MockObjectEncoderMockRecorder is the mock recorder for MockObjectEncoder.
type MockObjectEncoderMockRecorder struct {
	mock *MockObjectEncoder
}

// NewMockObjectEncoder creates a new mock instance.
func NewMockObjectEncoder(ctrl *gomock.Controller) *MockObjectEncoder {
	mock := &MockObjectEncoder{ctrl: ctrl}
	mock.recorder = &MockObjectEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectEncoder) EXPECT() *MockObjectEncoderMockRecorder {
	return m.recorder
}

// AddArray mocks base method.
func (m *MockObjectEncoder) AddArray(key string, marshaler zapcore.ArrayMarshaler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddArray", key, marshaler)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddArray indicates an expected call of AddArray.
func (mr *MockObjectEncoderMockRecorder) AddArray(key, marshaler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddArray", reflect.TypeOf((*MockObjectEncoder)(nil).AddArray), key, marshaler)
}

// AddBinary mocks base method.
func (m *MockObjectEncoder) AddBinary(key string, value []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBinary", key, value)
}

// AddBinary indicates an expected call of AddBinary.
func (mr *MockObjectEncoderMockRecorder) AddBinary(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBinary", reflect.TypeOf((*MockObjectEncoder)(nil).AddBinary), key, value)
}

// AddBool mocks base method.
func (m *MockObjectEncoder) AddBool(key string, value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBool", key, value)
}

// AddBool indicates an expected call of AddBool.
func (mr *MockObjectEncoderMockRecorder) AddBool(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBool", reflect.TypeOf((*MockObjectEncoder)(nil).AddBool), key, value)
}

// AddByteString mocks base method.
func (m *MockObjectEncoder) AddByteString(key string, value []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddByteString", key, value)
}

// AddByteString indicates an expected call of AddByteString.
func (mr *MockObjectEncoderMockRecorder) AddByteString(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddByteString", reflect.TypeOf((*MockObjectEncoder)(nil).AddByteString), key, value)
}

// AddComplex128 mocks base method.
func (m *MockObjectEncoder) AddComplex128(key string, value complex128) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddComplex128", key, value)
}

// AddComplex128 indicates an expected call of AddComplex128.
func (mr *MockObjectEncoderMockRecorder) AddComplex128(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComplex128", reflect.TypeOf((*MockObjectEncoder)(nil).AddComplex128), key, value)
}

// AddComplex64 mocks base method.
func (m *MockObjectEncoder) AddComplex64(key string, value complex64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddComplex64", key, value)
}

// AddComplex64 indicates an expected call of AddComplex64.
func (mr *MockObjectEncoderMockRecorder) AddComplex64(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComplex64", reflect.TypeOf((*MockObjectEncoder)(nil).AddComplex64), key, value)
}

// AddDuration mocks base method.
func (m *MockObjectEncoder) AddDuration(key string, value time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDuration", key, value)
}

// AddDuration indicates an expected call of AddDuration.
func (mr *MockObjectEncoderMockRecorder) AddDuration(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDuration", reflect.TypeOf((*MockObjectEncoder)(nil).AddDuration), key, value)
}

// AddFloat32 mocks base method.
func (m *MockObjectEncoder) AddFloat32(key string, value float32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFloat32", key, value)
}

// AddFloat32 indicates an expected call of AddFloat32.
func (mr *MockObjectEncoderMockRecorder) AddFloat32(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFloat32", reflect.TypeOf((*MockObjectEncoder)(nil).AddFloat32), key, value)
}

// AddFloat64 mocks base method.
func (m *MockObjectEncoder) AddFloat64(key string, value float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFloat64", key, value)
}

// AddFloat64 indicates an expected call of AddFloat64.
func (mr *MockObjectEncoderMockRecorder) AddFloat64(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFloat64", reflect.TypeOf((*MockObjectEncoder)(nil).AddFloat64), key, value)
}

// AddInt mocks base method.
func (m *MockObjectEncoder) AddInt(key string, value int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddInt", key, value)
}

// AddInt indicates an expected call of AddInt.
func (mr *MockObjectEncoderMockRecorder) AddInt(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt", reflect.TypeOf((*MockObjectEncoder)(nil).AddInt), key, value)
}

// AddInt16 mocks base method.
func (m *MockObjectEncoder) AddInt16(key string, value int16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddInt16", key, value)
}

// AddInt16 indicates an expected call of AddInt16.
func (mr *MockObjectEncoderMockRecorder) AddInt16(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt16", reflect.TypeOf((*MockObjectEncoder)(nil).AddInt16), key, value)
}

// AddInt32 mocks base method.
func (m *MockObjectEncoder) AddInt32(key string, value int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddInt32", key, value)
}

// AddInt32 indicates an expected call of AddInt32.
func (mr *MockObjectEncoderMockRecorder) AddInt32(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt32", reflect.TypeOf((*MockObjectEncoder)(nil).AddInt32), key, value)
}

// AddInt64 mocks base method.
func (m *MockObjectEncoder) AddInt64(key string, value int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddInt64", key, value)
}

// AddInt64 indicates an expected call of AddInt64.
func (mr *MockObjectEncoderMockRecorder) AddInt64(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt64", reflect.TypeOf((*MockObjectEncoder)(nil).AddInt64), key, value)
}

// AddInt8 mocks base method.
func (m *MockObjectEncoder) AddInt8(key string, value int8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddInt8", key, value)
}

// AddInt8 indicates an expected call of AddInt8.
func (mr *MockObjectEncoderMockRecorder) AddInt8(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt8", reflect.TypeOf((*MockObjectEncoder)(nil).AddInt8), key, value)
}

// AddObject mocks base method.
func (m *MockObjectEncoder) AddObject(key string, marshaler zapcore.ObjectMarshaler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddObject", key, marshaler)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddObject indicates an expected call of AddObject.
func (mr *MockObjectEncoderMockRecorder) AddObject(key, marshaler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddObject", reflect.TypeOf((*MockObjectEncoder)(nil).AddObject), key, marshaler)
}

// AddReflected mocks base method.
func (m *MockObjectEncoder) AddReflected(key string, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReflected", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReflected indicates an expected call of AddReflected.
func (mr *MockObjectEncoderMockRecorder) AddReflected(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReflected", reflect.TypeOf((*MockObjectEncoder)(nil).AddReflected), key, value)
}

// AddString mocks base method.
func (m *MockObjectEncoder) AddString(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddString", key, value)
}

// AddString indicates an expected call of AddString.
func (mr *MockObjectEncoderMockRecorder) AddString(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddString", reflect.TypeOf((*MockObjectEncoder)(nil).AddString), key, value)
}

// AddTime mocks base method.
func (m *MockObjectEncoder) AddTime(key string, value time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTime", key, value)
}

// AddTime indicates an expected call of AddTime.
func (mr *MockObjectEncoderMockRecorder) AddTime(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTime", reflect.TypeOf((*MockObjectEncoder)(nil).AddTime), key, value)
}

// AddUint mocks base method.
func (m *MockObjectEncoder) AddUint(key string, value uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUint", key, value)
}

// AddUint indicates an expected call of AddUint.
func (mr *MockObjectEncoderMockRecorder) AddUint(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUint", reflect.TypeOf((*MockObjectEncoder)(nil).AddUint), key, value)
}

// AddUint16 mocks base method.
func (m *MockObjectEncoder) AddUint16(key string, value uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUint16", key, value)
}

// AddUint16 indicates an expected call of AddUint16.
func (mr *MockObjectEncoderMockRecorder) AddUint16(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUint16", reflect.TypeOf((*MockObjectEncoder)(nil).AddUint16), key, value)
}

// AddUint32 mocks base method.
func (m *MockObjectEncoder) AddUint32(key string, value uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUint32", key, value)
}

// AddUint32 indicates an expected call of AddUint32.
func (mr *MockObjectEncoderMockRecorder) AddUint32(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUint32", reflect.TypeOf((*MockObjectEncoder)(nil).AddUint32), key, value)
}

// AddUint64 mocks base method.
func (m *MockObjectEncoder) AddUint64(key string, value uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUint64", key, value)
}

// AddUint64 indicates an expected call of AddUint64.
func (mr *MockObjectEncoderMockRecorder) AddUint64(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUint64", reflect.TypeOf((*MockObjectEncoder)(nil).AddUint64), key, value)
}

// AddUint8 mocks base method.
func (m *MockObjectEncoder) AddUint8(key string, value uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUint8", key, value)
}

// AddUint8 indicates an expected call of AddUint8.
func (mr *MockObjectEncoderMockRecorder) AddUint8(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUint8", reflect.TypeOf((*MockObjectEncoder)(nil).AddUint8), key, value)
}

// AddUintptr mocks base method.
func (m *MockObjectEncoder) AddUintptr(key string, value uintptr) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUintptr", key, value)
}

// AddUintptr indicates an expected call of AddUintptr.
func (mr *MockObjectEncoderMockRecorder) AddUintptr(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUintptr", reflect.TypeOf((*MockObjectEncoder)(nil).AddUintptr), key, value)
}

// OpenNamespace mocks base method.
func (m *MockObjectEncoder) OpenNamespace(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OpenNamespace", key)
}

// OpenNamespace indicates an expected call of OpenNamespace.
func (mr *MockObjectEncoderMockRecorder) OpenNamespace(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenNamespace", reflect.TypeOf((*MockObjectEncoder)(nil).OpenNamespace), key)
}

// MockArrayEncoder is a mock of ArrayEncoder interface.
type MockArrayEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockArrayEncoderMockRecorder
}

// MockArrayEncoderMockRecorder is the mock recorder for MockArrayEncoder.
type MockArrayEncoderMockRecorder struct {
	mock *MockArrayEncoder
}

// NewMockArrayEncoder creates a new mock instance.
func NewMockArrayEncoder(ctrl *gomock.Controller) *MockArrayEncoder {
	mock := &MockArrayEncoder{ctrl: ctrl}
	mock.recorder = &MockArrayEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrayEncoder) EXPECT() *MockArrayEncoderMockRecorder {
	return m.recorder
}

// AppendArray mocks base method.
func (m *MockArrayEncoder) AppendArray(arg0 zapcore.ArrayMarshaler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendArray", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendArray indicates an expected call of AppendArray.
func (mr *MockArrayEncoderMockRecorder) AppendArray(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendArray", reflect.TypeOf((*MockArrayEncoder)(nil).AppendArray), arg0)
}

// AppendBool mocks base method.
func (m *MockArrayEncoder) AppendBool(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendBool", arg0)
}

// AppendBool indicates an expected call of AppendBool.
func (mr *MockArrayEncoderMockRecorder) AppendBool(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendBool", reflect.TypeOf((*MockArrayEncoder)(nil).AppendBool), arg0)
}

// AppendByteString mocks base method.
func (m *MockArrayEncoder) AppendByteString(arg0 []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendByteString", arg0)
}

// AppendByteString indicates an expected call of AppendByteString.
func (mr *MockArrayEncoderMockRecorder) AppendByteString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendByteString", reflect.TypeOf((*MockArrayEncoder)(nil).AppendByteString), arg0)
}

// AppendComplex128 mocks base method.
func (m *MockArrayEncoder) AppendComplex128(arg0 complex128) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendComplex128", arg0)
}

// AppendComplex128 indicates an expected call of AppendComplex128.
func (mr *MockArrayEncoderMockRecorder) AppendComplex128(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendComplex128", reflect.TypeOf((*MockArrayEncoder)(nil).AppendComplex128), arg0)
}

// AppendComplex64 mocks base method.
func (m *MockArrayEncoder) AppendComplex64(arg0 complex64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendComplex64", arg0)
}

// AppendComplex64 indicates an expected call of AppendComplex64.
func (mr *MockArrayEncoderMockRecorder) AppendComplex64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendComplex64", reflect.TypeOf((*MockArrayEncoder)(nil).AppendComplex64), arg0)
}

// AppendDuration mocks base method.
func (m *MockArrayEncoder) AppendDuration(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendDuration", arg0)
}

// AppendDuration indicates an expected call of AppendDuration.
func (mr *MockArrayEncoderMockRecorder) AppendDuration(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendDuration", reflect.TypeOf((*MockArrayEncoder)(nil).AppendDuration), arg0)
}

// AppendFloat32 mocks base method.
func (m *MockArrayEncoder) AppendFloat32(arg0 float32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendFloat32", arg0)
}

// AppendFloat32 indicates an expected call of AppendFloat32.
func (mr *MockArrayEncoderMockRecorder) AppendFloat32(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendFloat32", reflect.TypeOf((*MockArrayEncoder)(nil).AppendFloat32), arg0)
}

// AppendFloat64 mocks base method.
func (m *MockArrayEncoder) AppendFloat64(arg0 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendFloat64", arg0)
}

// AppendFloat64 indicates an expected call of AppendFloat64.
func (mr *MockArrayEncoderMockRecorder) AppendFloat64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendFloat64", reflect.TypeOf((*MockArrayEncoder)(nil).AppendFloat64), arg0)
}

// AppendInt mocks base method.
func (m *MockArrayEncoder) AppendInt(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendInt", arg0)
}

// AppendInt indicates an expected call of AppendInt.
func (mr *MockArrayEncoderMockRecorder) AppendInt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInt", reflect.TypeOf((*MockArrayEncoder)(nil).AppendInt), arg0)
}

// AppendInt16 mocks base method.
func (m *MockArrayEncoder) AppendInt16(arg0 int16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendInt16", arg0)
}

// AppendInt16 indicates an expected call of AppendInt16.
func (mr *MockArrayEncoderMockRecorder) AppendInt16(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInt16", reflect.TypeOf((*MockArrayEncoder)(nil).AppendInt16), arg0)
}

// AppendInt32 mocks base method.
func (m *MockArrayEncoder) AppendInt32(arg0 int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendInt32", arg0)
}

// AppendInt32 indicates an expected call of AppendInt32.
func (mr *MockArrayEncoderMockRecorder) AppendInt32(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInt32", reflect.TypeOf((*MockArrayEncoder)(nil).AppendInt32), arg0)
}

// AppendInt64 mocks base method.
func (m *MockArrayEncoder) AppendInt64(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendInt64", arg0)
}

// AppendInt64 indicates an expected call of AppendInt64.
func (mr *MockArrayEncoderMockRecorder) AppendInt64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInt64", reflect.TypeOf((*MockArrayEncoder)(nil).AppendInt64), arg0)
}

// AppendInt8 mocks base method.
func (m *MockArrayEncoder) AppendInt8(arg0 int8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendInt8", arg0)
}

// AppendInt8 indicates an expected call of AppendInt8.
func (mr *MockArrayEncoderMockRecorder) AppendInt8(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInt8", reflect.TypeOf((*MockArrayEncoder)(nil).AppendInt8), arg0)
}

// AppendObject mocks base method.
func (m *MockArrayEncoder) AppendObject(arg0 zapcore.ObjectMarshaler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendObject", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendObject indicates an expected call of AppendObject.
func (mr *MockArrayEncoderMockRecorder) AppendObject(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendObject", reflect.TypeOf((*MockArrayEncoder)(nil).AppendObject), arg0)
}

// AppendReflected mocks base method.
func (m *MockArrayEncoder) AppendReflected(value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendReflected", value)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendReflected indicates an expected call of AppendReflected.
func (mr *MockArrayEncoderMockRecorder) AppendReflected(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendReflected", reflect.TypeOf((*MockArrayEncoder)(nil).AppendReflected), value)
}

// AppendString mocks base method.
func (m *MockArrayEncoder) AppendString(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendString", arg0)
}

// AppendString indicates an expected call of AppendString.
func (mr *MockArrayEncoderMockRecorder) AppendString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendString", reflect.TypeOf((*MockArrayEncoder)(nil).AppendString), arg0)
}

// AppendTime mocks base method.
func (m *MockArrayEncoder) AppendTime(arg0 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendTime", arg0)
}

// AppendTime indicates an expected call of AppendTime.
func (mr *MockArrayEncoderMockRecorder) AppendTime(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendTime", reflect.TypeOf((*MockArrayEncoder)(nil).AppendTime), arg0)
}

// AppendUint mocks base method.
func (m *MockArrayEncoder) AppendUint(arg0 uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUint", arg0)
}

// AppendUint indicates an expected call of AppendUint.
func (mr *MockArrayEncoderMockRecorder) AppendUint(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUint", reflect.TypeOf((*MockArrayEncoder)(nil).AppendUint), arg0)
}

// AppendUint16 mocks base method.
func (m *MockArrayEncoder) AppendUint16(arg0 uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUint16", arg0)
}

// AppendUint16 indicates an expected call of AppendUint16.
func (mr *MockArrayEncoderMockRecorder) AppendUint16(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUint16", reflect.TypeOf((*MockArrayEncoder)(nil).AppendUint16), arg0)
}

// AppendUint32 mocks base method.
func (m *MockArrayEncoder) AppendUint32(arg0 uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUint32", arg0)
}

// AppendUint32 indicates an expected call of AppendUint32.
func (mr *MockArrayEncoderMockRecorder) AppendUint32(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUint32", reflect.TypeOf((*MockArrayEncoder)(nil).AppendUint32), arg0)
}

// AppendUint64 mocks base method.
func (m *MockArrayEncoder) AppendUint64(arg0 uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUint64", arg0)
}

// AppendUint64 indicates an expected call of AppendUint64.
func (mr *MockArrayEncoderMockRecorder) AppendUint64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUint64", reflect.TypeOf((*MockArrayEncoder)(nil).AppendUint64), arg0)
}

// AppendUint8 mocks base method.
func (m *MockArrayEncoder) AppendUint8(arg0 uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUint8", arg0)
}

// AppendUint8 indicates an expected call of AppendUint8.
func (mr *MockArrayEncoderMockRecorder) AppendUint8(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUint8", reflect.TypeOf((*MockArrayEncoder)(nil).AppendUint8), arg0)
}

// AppendUintptr mocks base method.
func (m *MockArrayEncoder) AppendUintptr(arg0 uintptr) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUintptr", arg0)
}

// AppendUintptr indicates an expected call of AppendUintptr.
func (mr *MockArrayEncoderMockRecorder) AppendUintptr(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUintptr", reflect.TypeOf((*MockArrayEncoder)(nil).AppendUintptr), arg0)
}

// MockPrimitiveArrayEncoder is a mock of PrimitiveArrayEncoder interface.
type MockPrimitiveArrayEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockPrimitiveArrayEncoderMockRecorder
}

// MockPrimitiveArrayEncoderMockRecorder is the mock recorder for MockPrimitiveArrayEncoder.
type MockPrimitiveArrayEncoderMockRecorder struct {
	mock *MockPrimitiveArrayEncoder
}

// NewMockPrimitiveArrayEncoder creates a new mock instance.
func NewMockPrimitiveArrayEncoder(ctrl *gomock.Controller) *MockPrimitiveArrayEncoder {
	mock := &MockPrimitiveArrayEncoder{ctrl: ctrl}
	mock.recorder = &MockPrimitiveArrayEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrimitiveArrayEncoder) EXPECT() *MockPrimitiveArrayEncoderMockRecorder {
	return m.recorder
}

// AppendBool mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendBool(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendBool", arg0)
}

// AppendBool indicates an expected call of AppendBool.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendBool(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendBool", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendBool), arg0)
}

// AppendByteString mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendByteString(arg0 []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendByteString", arg0)
}

// AppendByteString indicates an expected call of AppendByteString.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendByteString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendByteString", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendByteString), arg0)
}

// AppendComplex128 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendComplex128(arg0 complex128) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendComplex128", arg0)
}

// AppendComplex128 indicates an expected call of AppendComplex128.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendComplex128(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendComplex128", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendComplex128), arg0)
}

// AppendComplex64 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendComplex64(arg0 complex64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendComplex64", arg0)
}

// AppendComplex64 indicates an expected call of AppendComplex64.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendComplex64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendComplex64", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendComplex64), arg0)
}

// AppendFloat32 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendFloat32(arg0 float32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendFloat32", arg0)
}

// AppendFloat32 indicates an expected call of AppendFloat32.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendFloat32(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendFloat32", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendFloat32), arg0)
}

// AppendFloat64 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendFloat64(arg0 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendFloat64", arg0)
}

// AppendFloat64 indicates an expected call of AppendFloat64.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendFloat64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendFloat64", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendFloat64), arg0)
}

// AppendInt mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendInt(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendInt", arg0)
}

// AppendInt indicates an expected call of AppendInt.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendInt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInt", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendInt), arg0)
}

// AppendInt16 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendInt16(arg0 int16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendInt16", arg0)
}

// AppendInt16 indicates an expected call of AppendInt16.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendInt16(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInt16", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendInt16), arg0)
}

// AppendInt32 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendInt32(arg0 int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendInt32", arg0)
}

// AppendInt32 indicates an expected call of AppendInt32.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendInt32(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInt32", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendInt32), arg0)
}

// AppendInt64 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendInt64(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendInt64", arg0)
}

// AppendInt64 indicates an expected call of AppendInt64.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendInt64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInt64", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendInt64), arg0)
}

// AppendInt8 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendInt8(arg0 int8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendInt8", arg0)
}

// AppendInt8 indicates an expected call of AppendInt8.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendInt8(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendInt8", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendInt8), arg0)
}

// AppendString mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendString(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendString", arg0)
}

// AppendString indicates an expected call of AppendString.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendString", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendString), arg0)
}

// AppendUint mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendUint(arg0 uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUint", arg0)
}

// AppendUint indicates an expected call of AppendUint.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendUint(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUint", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendUint), arg0)
}

// AppendUint16 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendUint16(arg0 uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUint16", arg0)
}

// AppendUint16 indicates an expected call of AppendUint16.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendUint16(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUint16", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendUint16), arg0)
}

// AppendUint32 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendUint32(arg0 uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUint32", arg0)
}

// AppendUint32 indicates an expected call of AppendUint32.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendUint32(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUint32", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendUint32), arg0)
}

// AppendUint64 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendUint64(arg0 uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUint64", arg0)
}

// AppendUint64 indicates an expected call of AppendUint64.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendUint64(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUint64", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendUint64), arg0)
}

// AppendUint8 mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendUint8(arg0 uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUint8", arg0)
}

// AppendUint8 indicates an expected call of AppendUint8.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendUint8(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUint8", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendUint8), arg0)
}

// AppendUintptr mocks base method.
func (m *MockPrimitiveArrayEncoder) AppendUintptr(arg0 uintptr) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendUintptr", arg0)
}

// AppendUintptr indicates an expected call of AppendUintptr.
func (mr *MockPrimitiveArrayEncoderMockRecorder) AppendUintptr(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendUintptr", reflect.TypeOf((*MockPrimitiveArrayEncoder)(nil).AppendUintptr), arg0)
}

// MockEncoder is a mock of Encoder interface.
type MockEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockEncoderMockRecorder
}

// MockEncoderMockRecorder is the mock recorder for MockEncoder.
type MockEncoderMockRecorder struct {
	mock *MockEncoder
}

// NewMockEncoder creates a new mock instance.
func NewMockEncoder(ctrl *gomock.Controller) *MockEncoder {
	mock := &MockEncoder{ctrl: ctrl}
	mock.recorder = &MockEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncoder) EXPECT() *MockEncoderMockRecorder {
	return m.recorder
}

// AddArray mocks base method.
func (m *MockEncoder) AddArray(key string, marshaler zapcore.ArrayMarshaler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddArray", key, marshaler)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddArray indicates an expected call of AddArray.
func (mr *MockEncoderMockRecorder) AddArray(key, marshaler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddArray", reflect.TypeOf((*MockEncoder)(nil).AddArray), key, marshaler)
}

// AddBinary mocks base method.
func (m *MockEncoder) AddBinary(key string, value []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBinary", key, value)
}

// AddBinary indicates an expected call of AddBinary.
func (mr *MockEncoderMockRecorder) AddBinary(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBinary", reflect.TypeOf((*MockEncoder)(nil).AddBinary), key, value)
}

// AddBool mocks base method.
func (m *MockEncoder) AddBool(key string, value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBool", key, value)
}

// AddBool indicates an expected call of AddBool.
func (mr *MockEncoderMockRecorder) AddBool(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBool", reflect.TypeOf((*MockEncoder)(nil).AddBool), key, value)
}

// AddByteString mocks base method.
func (m *MockEncoder) AddByteString(key string, value []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddByteString", key, value)
}

// AddByteString indicates an expected call of AddByteString.
func (mr *MockEncoderMockRecorder) AddByteString(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddByteString", reflect.TypeOf((*MockEncoder)(nil).AddByteString), key, value)
}

// AddComplex128 mocks base method.
func (m *MockEncoder) AddComplex128(key string, value complex128) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddComplex128", key, value)
}

// AddComplex128 indicates an expected call of AddComplex128.
func (mr *MockEncoderMockRecorder) AddComplex128(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComplex128", reflect.TypeOf((*MockEncoder)(nil).AddComplex128), key, value)
}

// AddComplex64 mocks base method.
func (m *MockEncoder) AddComplex64(key string, value complex64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddComplex64", key, value)
}

// AddComplex64 indicates an expected call of AddComplex64.
func (mr *MockEncoderMockRecorder) AddComplex64(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComplex64", reflect.TypeOf((*MockEncoder)(nil).AddComplex64), key, value)
}

// AddDuration mocks base method.
func (m *MockEncoder) AddDuration(key string, value time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDuration", key, value)
}

// AddDuration indicates an expected call of AddDuration.
func (mr *MockEncoderMockRecorder) AddDuration(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDuration", reflect.TypeOf((*MockEncoder)(nil).AddDuration), key, value)
}

// AddFloat32 mocks base method.
func (m *MockEncoder) AddFloat32(key string, value float32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFloat32", key, value)
}

// AddFloat32 indicates an expected call of AddFloat32.
func (mr *MockEncoderMockRecorder) AddFloat32(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFloat32", reflect.TypeOf((*MockEncoder)(nil).AddFloat32), key, value)
}

// AddFloat64 mocks base method.
func (m *MockEncoder) AddFloat64(key string, value float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFloat64", key, value)
}

// AddFloat64 indicates an expected call of AddFloat64.
func (mr *MockEncoderMockRecorder) AddFloat64(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFloat64", reflect.TypeOf((*MockEncoder)(nil).AddFloat64), key, value)
}

// AddInt mocks base method.
func (m *MockEncoder) AddInt(key string, value int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddInt", key, value)
}

// AddInt indicates an expected call of AddInt.
func (mr *MockEncoderMockRecorder) AddInt(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt", reflect.TypeOf((*MockEncoder)(nil).AddInt), key, value)
}

// AddInt16 mocks base method.
func (m *MockEncoder) AddInt16(key string, value int16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddInt16", key, value)
}

// AddInt16 indicates an expected call of AddInt16.
func (mr *MockEncoderMockRecorder) AddInt16(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt16", reflect.TypeOf((*MockEncoder)(nil).AddInt16), key, value)
}

// AddInt32 mocks base method.
func (m *MockEncoder) AddInt32(key string, value int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddInt32", key, value)
}

// AddInt32 indicates an expected call of AddInt32.
func (mr *MockEncoderMockRecorder) AddInt32(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt32", reflect.TypeOf((*MockEncoder)(nil).AddInt32), key, value)
}

// AddInt64 mocks base method.
func (m *MockEncoder) AddInt64(key string, value int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddInt64", key, value)
}

// AddInt64 indicates an expected call of AddInt64.
func (mr *MockEncoderMockRecorder) AddInt64(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt64", reflect.TypeOf((*MockEncoder)(nil).AddInt64), key, value)
}

// AddInt8 mocks base method.
func (m *MockEncoder) AddInt8(key string, value int8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddInt8", key, value)
}

// AddInt8 indicates an expected call of AddInt8.
func (mr *MockEncoderMockRecorder) AddInt8(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInt8", reflect.TypeOf((*MockEncoder)(nil).AddInt8), key, value)
}

// AddObject mocks base method.
func (m *MockEncoder) AddObject(key string, marshaler zapcore.ObjectMarshaler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddObject", key, marshaler)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddObject indicates an expected call of AddObject.
func (mr *MockEncoderMockRecorder) AddObject(key, marshaler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddObject", reflect.TypeOf((*MockEncoder)(nil).AddObject), key, marshaler)
}

// AddReflected mocks base method.
func (m *MockEncoder) AddReflected(key string, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReflected", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReflected indicates an expected call of AddReflected.
func (mr *MockEncoderMockRecorder) AddReflected(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReflected", reflect.TypeOf((*MockEncoder)(nil).AddReflected), key, value)
}

// AddString mocks base method.
func (m *MockEncoder) AddString(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddString", key, value)
}

// AddString indicates an expected call of AddString.
func (mr *MockEncoderMockRecorder) AddString(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddString", reflect.TypeOf((*MockEncoder)(nil).AddString), key, value)
}

// AddTime mocks base method.
func (m *MockEncoder) AddTime(key string, value time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTime", key, value)
}

// AddTime indicates an expected call of AddTime.
func (mr *MockEncoderMockRecorder) AddTime(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTime", reflect.TypeOf((*MockEncoder)(nil).AddTime), key, value)
}

// AddUint mocks base method.
func (m *MockEncoder) AddUint(key string, value uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUint", key, value)
}

// AddUint indicates an expected call of AddUint.
func (mr *MockEncoderMockRecorder) AddUint(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUint", reflect.TypeOf((*MockEncoder)(nil).AddUint), key, value)
}

// AddUint16 mocks base method.
func (m *MockEncoder) AddUint16(key string, value uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUint16", key, value)
}

// AddUint16 indicates an expected call of AddUint16.
func (mr *MockEncoderMockRecorder) AddUint16(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUint16", reflect.TypeOf((*MockEncoder)(nil).AddUint16), key, value)
}

// AddUint32 mocks base method.
func (m *MockEncoder) AddUint32(key string, value uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUint32", key, value)
}

// AddUint32 indicates an expected call of AddUint32.
func (mr *MockEncoderMockRecorder) AddUint32(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUint32", reflect.TypeOf((*MockEncoder)(nil).AddUint32), key, value)
}

// AddUint64 mocks base method.
func (m *MockEncoder) AddUint64(key string, value uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUint64", key, value)
}

// AddUint64 indicates an expected call of AddUint64.
func (mr *MockEncoderMockRecorder) AddUint64(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUint64", reflect.TypeOf((*MockEncoder)(nil).AddUint64), key, value)
}

// AddUint8 mocks base method.
func (m *MockEncoder) AddUint8(key string, value uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUint8", key, value)
}

// AddUint8 indicates an expected call of AddUint8.
func (mr *MockEncoderMockRecorder) AddUint8(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUint8", reflect.TypeOf((*MockEncoder)(nil).AddUint8), key, value)
}

// AddUintptr mocks base method.
func (m *MockEncoder) AddUintptr(key string, value uintptr) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUintptr", key, value)
}

// AddUintptr indicates an expected call of AddUintptr.
func (mr *MockEncoderMockRecorder) AddUintptr(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUintptr", reflect.TypeOf((*MockEncoder)(nil).AddUintptr), key, value)
}

// Clone mocks base method.
func (m *MockEncoder) Clone() zapcore.Encoder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone")
	ret0, _ := ret[0].(zapcore.Encoder)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockEncoderMockRecorder) Clone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockEncoder)(nil).Clone))
}

// EncodeEntry mocks base method.
func (m *MockEncoder) EncodeEntry(arg0 zapcore.Entry, arg1 []zapcore.Field) (*buffer.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeEntry", arg0, arg1)
	ret0, _ := ret[0].(*buffer.Buffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncodeEntry indicates an expected call of EncodeEntry.
func (mr *MockEncoderMockRecorder) EncodeEntry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeEntry", reflect.TypeOf((*MockEncoder)(nil).EncodeEntry), arg0, arg1)
}

// OpenNamespace mocks base method.
func (m *MockEncoder) OpenNamespace(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OpenNamespace", key)
}

// OpenNamespace indicates an expected call of OpenNamespace.
func (mr *MockEncoderMockRecorder) OpenNamespace(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenNamespace", reflect.TypeOf((*MockEncoder)(nil).OpenNamespace), key)
}
